spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


comment.avatar: /images/avatar.png

---

# redis configuration
spring:
  redis:
    database: 0
    host: 120.78.158.142
    port: 6379
    password:

